# Generated by Django 5.1.4 on 2024-12-22 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_profile_next_of_kin_address_and_more'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_appointment_patient', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_assignments', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='doctorpatientmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='emergencyalert',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_claims', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_medical_records', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_prescriptions', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='progresstracking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='teammessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_received_messages', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='patients.patient'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'scheduled_time'), name='unique_appointment'),
        ),
    ]
