# Generated by Django 5.1.4 on 2024-12-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_careplan_patient_alter_teammessage_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
