# Generated by Django 5.1.4 on 2024-12-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffmessage_is_read_staffmessage_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorpatientmessage',
            name='patient_reply',
            field=models.CharField(default='', max_length=500),
        ),
    ]
