# Generated by Django 5.1.4 on 2024-12-29 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_doctor'),
        ('patients', '0007_remove_profile_modified_by'),
        ('staff', '0005_doctorpatientmessage_patient_reply'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='patient',
            new_name='staff_patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='reason',
            new_name='staff_reason',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='scheduled_time',
            new_name='staff_scheduled_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='status',
            new_name='staff_status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='linked_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_appointment', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='staff_doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='staff_appointments_assigned', to='staff.staff'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('staff_patient', 'staff_doctor', 'staff_scheduled_time'), name='unique_staff_appointment'),
        ),
    ]
