# Generated by Django 5.1.4 on 2024-12-29 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_doctor'),
        ('patients', '0007_remove_profile_modified_by'),
        ('staff', '0006_remove_appointment_unique_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_staff_appointment',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='staff_patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='staff_reason',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='staff_scheduled_time',
            new_name='scheduled_time',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='staff_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='staff_doctor',
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='appointments_assigned', to='staff.staff'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='linked_appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_appointment', to='appointments.appointment'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('patient', 'doctor', 'scheduled_time'), name='unique_appointment'),
        ),
    ]
