# Generated by Django 5.1.4 on 2024-12-30 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_appointment_created_by_doctorschedule_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_schedule', to='staff.staff'),
        ),
    ]
