# Generated by Django 5.1.4 on 2024-12-31 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_profile_modified_by'),
        ('staff', '0011_alter_auditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated_for',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='patients.patient'),
            preserve_default=False,
        ),
    ]
