# Generated by Django 5.1.4 on 2025-01-15 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_tokenlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
