# Generated by Django 5.1.4 on 2025-01-15 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_alter_tokenlog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to='staff.staff'),
        ),
    ]
