# Generated by Django 5.1.4 on 2024-12-24 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_patient'),
        ('staff', '0002_alter_appointment_patient_alter_appointment_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
