# Generated by Django 5.1.4 on 2024-12-29 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_reschedule_request_date_and_more'),
        ('staff', '0005_doctorpatientmessage_patient_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to='staff.staff'),
        ),
    ]
