# Generated by Django 5.1.4 on 2024-12-22 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_profile_next_of_kin_address_and_more'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_medical_records', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records_prescriptions', to='patients.patient'),
        ),
    ]
