# Generated by Django 5.1.4 on 2024-12-24 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_profile_next_of_kin_address_and_more'),
        ('staff', '0002_alter_appointment_patient_alter_appointment_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyservice',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='medicationreminder',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_reminders', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_profiles', to='staff.staff'),
        ),
        migrations.AlterField(
            model_name='treatmentplan',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to='patients.patient'),
        ),
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
