# Generated by Django 5.1.4 on 2024-12-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='modified_by',
        ),
    ]
